# Generated by Django 5.2.4 on 2025-07-29 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, db_column='last_updated_at')),
                ('apiToken', models.CharField(db_column='api_token', max_length=255)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openID', models.IntegerField(db_column='openID')),
                ('token', models.CharField(db_column='token', max_length=255)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('status', models.CharField(db_column='status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, db_column='last_updated_at')),
                ('created_by', models.CharField(db_column='created_by', max_length=255)),
                ('externalID', models.CharField(db_column='externalID', max_length=255, null=True)),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Signatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_column='token', max_length=255)),
                ('status', models.CharField(db_column='status', max_length=50)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('email', models.EmailField(db_column='email', max_length=255)),
                ('externalID', models.CharField(db_column='externalID', max_length=255, null=True)),
                ('documentID', models.ForeignKey(db_column='documentID', on_delete=django.db.models.deletion.CASCADE, to='api.documento')),
            ],
            options={
                'verbose_name': 'Signer',
                'verbose_name_plural': 'Signers',
                'db_table': 'signers',
            },
        ),
    ]
