services:
  angular-frontend:
    build: .
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
